"""
Deployment Agent (Phase 10)
Converts final system to MQL5 Expert Advisor template.
- Reads optimized parameters
- Generates MQL5 source with regime-aware logic
- Not a full EA, but a structured template for MT5
"""
from __future__ import annotations

import logging
from typing import Optional, Dict, Any
from pathlib import Path

from core.base_agent import BaseAgent, AgentResult
from core.state_store import StateStore
from core.message_bus import MessageBus

logger = logging.getLogger(__name__)

MQL5_TEMPLATE = '''//+------------------------------------------------------------------+
//|                                      AutoGen_RegimeEA_v1.mq5     |
//|                        Auto-generated by QuantResearchOrg         |
//|                                                                    |
//+------------------------------------------------------------------+
#property copyright "QuantResearchOrg"
#property link      ""
#property version   "1.00"

input group "=== Regime Parameters ==="
input double InpMinConfidence = {min_confidence};
input bool   InpFilterTransitions = {filter_transitions};
input bool   InpFilterRange = {filter_range};
input double InpAtrMultSL = {atr_sl};
input double InpAtrMultTP = {atr_tp};

input group "=== Risk Parameters ==="
input double InpRiskPerTrade = 0.02;
input double InpMaxDrawdown = 0.15;

//+------------------------------------------------------------------+
int OnInit()
{{
   // TODO: Initialize regime feature computation (EMA stack, ADX proxy)
   // TODO: Connect to Redis or internal state store for regime sync
   Print("RegimeEA initialized. MinConfidence=", InpMinConfidence);
   return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
void OnTick()
{{
   // 1. Compute structural EMAs (50, 100, 200)
   // 2. Compute tactical EMAs (7, 21, 34)
   // 3. Compute RSI(14) and ADX proxy
   // 4. Classify regime using same logic as Python RegimeAgent
   // 5. If regime confidence >= InpMinConfidence and not transition:
   //      - Generate signal aligned with regime
   //      - Calculate ATR-based SL/TP
   //      - Submit order with risk-adjusted lot size
   // 6. If drawdown > InpMaxDrawdown: halt trading
}}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   Print("RegimeEA stopped. Reason=", reason);
}}
'''

class DeploymentAgent(BaseAgent):
    """
    Owns the constraint: PRODUCTION READINESS.
    """

    def __init__(self, state_store: StateStore, message_bus: MessageBus, output_dir: str = "./output/mql5"):
        super().__init__("deployment_agent", state_store, message_bus)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def execute(self, input_artifact_id: Optional[str] = None, **kwargs) -> AgentResult:
        logger.info("[DeploymentAgent] Generating MQL5 deployment artifact...")

        try:
            if not input_artifact_id:
                return AgentResult(success=False, message="DeploymentAgent requires optimization artifact")

            artifact = self.store.load(input_artifact_id)
            bundle = artifact.data
            params = bundle.get("params", {}) if isinstance(bundle, dict) else {}

            mql5_code = MQL5_TEMPLATE.format(
                min_confidence=params.get("min_confidence", 0.60),
                filter_transitions="true" if params.get("filter_transitions", True) else "false",
                filter_range="true" if params.get("filter_range", False) else "false",
                atr_sl=params.get("atr_multiplier_sl", 1.5),
                atr_tp=params.get("atr_multiplier_tp", 3.0),
            )

            file_path = self.output_dir / "AutoGen_RegimeEA_v1.mq5"
            with open(file_path, "w") as f:
                f.write(mql5_code)

            artifact_id = self._produce_artifact(
                name="mql5_ea_template",
                data={
                    "mql5_code": mql5_code,
                    "file_path": str(file_path),
                    "params": params,
                },
                phase="deployment",
                parent_artifact=input_artifact_id,
                tags=["mql5", "deployment", "mt5"],
                notes=f"MQL5 EA written to {file_path}",
            )

            return AgentResult(
                success=True,
                artifact_id=artifact_id,
                message=f"MQL5 EA template generated at {file_path}",
                diagnostics={"file": str(file_path), "lines": len(mql5_code.splitlines())},
            )

        except Exception as e:
            logger.exception("[DeploymentAgent] Fatal error")
            return AgentResult(success=False, message=str(e), halt_pipeline=True)
